rootProject.name = "ArcCore"

include("arc-core")
include("arc-core-menu")
include("arc-core-logging")
include("arc-core-metrics")
include("arc-core-redis")
include("arc-core-sql")
include("arc-core-paper")
include("arc-core-paper-menu")
include("arc-core-testing")
include("arc-core-paper-testing")
include("arc-core-integration-testing")
include("arc-core-velocity")
include("arc-core-ai")
include("arc-core-ops")
include("arc-core-ops-paper")
include("arc-core-ops-velocity")
